# use Travis CI to generate and deploy blog to github pages automatically
language: node_js
node_js:
  - "node"
before_script:
  - npm install pencil --global
script: pencil generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  on:
    branch: master