# site
site:
    host: http://zhouzh.me
    title: pencil
    keywords: ['software', 'development']
    description: description of site
    author: zhouzh1
    avatar: image url of avatar
    rssSize: 10 # count of items to be added rss.xml
    pageSize: 1 # count of items in index page
    theme: default # theme of blog
    copyright: 2017 powered by pencil
# contact
contact:
    email: zzhouzhii@gmail.com
    github: https://github.com/zhouzh1
    weibo:  http://www.weibo.com
    twitter: http://www.twitter.com
    facebook: http://www.facebook.com
# other configuration
