# deploy to github page
language: node_js
node_js:
 - "node"
branches:
  only:
    - source
env:
  - GITHUB_USERNAME=zhouzh1
  - GITHUB_EMAIL=zzhouzhii@gmail.com
  - GITHUB_REPOSITORY=zhouzh1.github.io.git
before_script:
 - npm install pencil-cli --global
script: pencil generate
after_success:
  - git config --global user.name $GITHUB_USERNAME
  - git config --global user.email $GITHUB_EMAIL
  - git remote origin set-url https://$GITHUB_USERNAME:<$GITHUB_TOKEN>@github.com/$GITHUB_USERNAME/$GITHUB_REPOSITORY
  - git add -A
  - git commit -m $TRAVIS_COMMIT_MESSAGE
  - git subtree push --prefix public origin master